let employeeHrState=null,employeeHrLoading=false,employeeHrPending=null,employeeHrQueued=false,employeeHrGeneration=0,employeeHrMutating=false,employeeHrChecking=false,employeeHrOffset=0;
const employeeHrChannel=typeof BroadcastChannel==='function'?new BroadcastChannel('newtel-hr-updates'):null;
function notifyEmployeeHr(){employeeHrChannel?.postMessage({changed:true})}
const employeeHrEsc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const employeeHrKinds={annual:'Annual leave',short_leave:'Hourly leave',schedule_preference:'Next-week preference',sick:'Sick leave'};
function employeeHrMessage(text,error=false){for(const id of ['employeeHrMessage','employeeHrProfileMessage']){const node=document.getElementById(id);if(node){node.textContent=text;node.classList.toggle('error',error)}}}
function employeeHrTime(value){return value?new Date(value).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Amman'}):'Not recorded'}
function employeeHrMinutes(value){const minutes=Math.max(0,Math.round(Number(value)||0));return Math.floor(minutes/60)+'h '+minutes%60+'m'}
function employeeHrBadge(status){return '<span class="employee-hr-status '+employeeHrEsc(status)+'">'+employeeHrEsc(status[0].toUpperCase()+status.slice(1))+'</span>'}
function updateEmployeeWork(){
  if(!employeeHrState)return;
  const d=employeeHrState,summary=globalThis.NewtelHrCore?.hrWorkSummary({day:d.day,shift:d.shift,attendance:d.attendance,leave:d.status==='sick_leave'?{status:'approved'}:null,requests:d.approved_requests||[],now:Date.now()+employeeHrOffset})||d.work_summary;
  if(!summary)return;
  const target=document.getElementById('employeeHrWorked');if(target)NewtelLiveDom.text(target,employeeHrMinutes(summary.work_minutes)+' / '+employeeHrMinutes(summary.required_minutes));
  const leave=document.getElementById('employeeHrApprovedTime');if(leave)NewtelLiveDom.text(leave,employeeHrMinutes(summary.approved_leave_minutes));
  const progress=document.getElementById('employeeHrProgress');if(progress){const max=Math.max(1,summary.required_minutes),value=Math.min(summary.work_minutes,max);if(progress.max!==max)progress.max=max;if(progress.value!==value)progress.value=value}
}
function renderEmployeeHr(preserveDraft=true){
  const node=document.getElementById('employeeHrCard');if(!node||!employeeHrState)return;
  const data=employeeHrState,record=data.attendance;
  NewtelLiveDom.html(node,'<header><div><span>START YOUR DAY</span><h2>My attendance</h2></div><small>'+employeeHrEsc(data.day)+'</small></header><div class="employee-hr-shift">Official shift: <strong>'+employeeHrEsc(data.shift||'Not scheduled')+'</strong></div><div class="employee-hr-times"><div><small>First check-in</small><strong>'+employeeHrTime(record?.punch_in)+'</strong></div><div><small>Check-out</small><strong>'+employeeHrTime(record?.punch_out)+'</strong></div><div><small>Worked / required</small><strong id="employeeHrWorked">—</strong></div><div><small>Approved time off</small><strong id="employeeHrApprovedTime">—</strong></div></div><progress id="employeeHrProgress" aria-label="Scheduled work progress" max="1" value="0"></progress><div class="employee-hr-buttons"><button type="button" data-hr-punch="in" '+(record?.punch_in||!data.shift||data.shift==='OFF'?'disabled':'')+'>Check in</button><button type="button" data-hr-punch="out" '+(!record?.punch_in||record?.punch_out?'disabled':'')+'>Check out</button></div>'+(data.late_minutes?'<p class="employee-hr-late">'+data.late_minutes+' minutes late against the saved shift.</p>':'')+'<p class="employee-hr-note">Your first daily punch is saved when you reopen eBook. Worked time is the punch interval inside the shift, excluding approved leave; it is not physical-presence verification.</p><div id="employeeHrMessage" role="status" aria-live="polite"></div>');
  node.querySelectorAll('[data-hr-punch]').forEach(button=>{
    // A failed request must restore controls even when markup is unchanged.
    button.disabled=button.dataset.hrPunch==='in'?!!record?.punch_in||!data.shift||data.shift==='OFF':!record?.punch_in||!!record?.punch_out;
    button.onclick=async()=>{
    if(employeeHrMutating)return;if(button.dataset.hrPunch==='out'&&!confirm('Record your attendance check-out?'))return;
    node.querySelectorAll('[data-hr-punch]').forEach(item=>item.disabled=true);employeeHrMutating=true;employeeHrGeneration++;
    try{const result=await NewtelHrApi.call('/punch',{method:'POST',body:{action:button.dataset.hrPunch}});employeeHrState={...employeeHrState,...result};renderEmployeeHr();notifyEmployeeHr();await loadEmployeeHr({force:true});employeeHrMessage('Attendance saved using server time.')}catch(error){renderEmployeeHr();employeeHrMessage(error.message,true)}finally{employeeHrMutating=false}
  }});
  updateEmployeeWork();renderEmployeeHrProfile(preserveDraft);showEmployeeHrAction();
}
function employeeHrRequestHistory(row){
  const type=row.request_type||'sick';let week=[];try{week=JSON.parse(row.week_json||'[]')}catch{}
  return '<article class="employee-hr-history-card" data-live-key="'+employeeHrEsc(type+':'+row.id)+'"><header><strong>'+employeeHrKinds[type]+'</strong>'+employeeHrBadge(row.status)+'</header><p>'+employeeHrEsc(row.start_date)+' → '+employeeHrEsc(row.end_date)+(type==='short_leave'?'<br>'+employeeHrEsc(row.start_time)+' – '+employeeHrEsc(row.end_time)+' · '+employeeHrMinutes(row.requested_minutes):'')+'</p>'+(row.note?'<p>'+employeeHrEsc(row.note)+'</p>':'')+(week.length?'<ul>'+week.map(d=>'<li>'+employeeHrEsc(d.day)+' · '+employeeHrEsc(d.value)+'</li>').join('')+'</ul>':'')+(row.reviewed_at?'<small>Reviewed '+employeeHrEsc(new Date(row.reviewed_at).toLocaleString('en-GB',{timeZone:'Asia/Amman'}))+'</small>':'')+'</article>';
}
function renderEmployeeHrProfile(preserveDraft=true){
  const node=document.getElementById('employeeHrProfile');if(!node)return;
  const d=employeeHrState,E=employeeHrEsc;
  if(preserveDraft)node.querySelectorAll('details[data-request-form]').forEach(item=>item.setAttribute('data-live-preserve',''));
  NewtelLiveDom.html(node,'<div class="employee-hr-profile-heading"><span>MY REQUESTS & RECORDS</span><h2>Time off & next week</h2><p>HR reviews each request. Approval notices appear automatically here and when you open eBook.</p></div><div id="employeeHrProfileMessage" role="status" aria-live="polite"></div><div class="employee-hr-request-grid">'+
    '<details class="employee-hr-leave" data-request-form="sick"><summary>Sick leave <span>Medical attachment</span></summary><form id="employeeSickForm"><label>From<input type="date" name="start_date" required value="'+d.today+'"></label><label>To<input type="date" name="end_date" required value="'+d.today+'"></label><label class="employee-hr-wide">PDF / JPG / PNG · up to 5 MB<input type="file" name="file" accept="application/pdf,image/jpeg,image/png" required></label><label class="employee-hr-wide">Note<textarea name="note" maxlength="1000"></textarea></label><button class="employee-hr-wide">Submit sick leave</button></form></details>'+
    '<details class="employee-hr-leave" data-request-form="annual"><summary>Annual leave <span>Full working days</span></summary><form id="employeeAnnualForm"><label>From<input name="start_date" type="date" value="'+d.today+'" required></label><label>To<input name="end_date" type="date" value="'+d.today+'" required></label><label class="employee-hr-wide">Note<textarea name="note" maxlength="1000"></textarea></label><p class="employee-hr-note employee-hr-wide">Leave entitlement is reviewed by HR. No automatic balance is assumed.</p><button class="employee-hr-wide">Request annual leave</button></form></details>'+
    '<details class="employee-hr-leave" data-request-form="short_leave"><summary>Hourly leave <span>1 hour, 2 hours or custom</span></summary><form id="employeeHourlyForm"><label class="employee-hr-wide">Shift date<input type="date" name="start_date" value="'+d.day+'" required></label><p class="employee-hr-wide employee-hr-note" id="employeeHourlyShift">Saved shift: '+E(d.shift||'Not scheduled')+'</p><label>Start<input type="time" name="start_time" required value="'+E(d.shift?.slice(0,5)||'')+'"></label><label>Duration<select name="duration"><option value="60">1 hour</option><option value="120">2 hours</option><option value="custom">Custom</option></select></label><label class="employee-hr-wide">End<input type="time" name="end_time" required></label><label class="employee-hr-wide">Reason<textarea name="note" maxlength="1000"></textarea></label><p class="employee-hr-note employee-hr-wide">Must fit inside the saved shift. Approved leave reduces required work, but never counts as worked hours.</p><button class="employee-hr-wide">Request hourly leave</button></form></details>'+
    '<details class="employee-hr-leave" data-request-form="schedule_preference"><summary>Next-week preference <span>Working shifts & days off</span></summary><form id="employeeWeekForm"><p class="employee-hr-wide employee-hr-note">Preferences are not your official schedule until HR approves and applies them.</p><div class="employee-hr-week employee-hr-wide">'+(d.next_week||[]).map(row=>'<div><strong>'+new Date(row.day+'T12:00:00Z').toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'})+'</strong><small>Saved: '+E(row.shift||'Not scheduled')+'</small><label>Preference<select data-week-day="'+row.day+'"><option value="">No preference</option><option value="OFF">Day off</option>'+Array.from({length:16},(_,i)=>{const start=String((8+i)%24).padStart(2,'0')+':00',end=String((17+i)%24).padStart(2,'0')+':00';return '<option value="'+start+' - '+end+'">'+String.fromCharCode(65+i)+' · '+start+' – '+end+'</option>'}).join('')+'<option value="custom">Custom shift</option></select></label><div data-week-custom hidden><label>Start<input type="time" data-week-start></label><label>End<input type="time" data-week-end></label></div></div>').join('')+'</div><label class="employee-hr-wide">Note<textarea name="note" maxlength="1000" placeholder="Your preferred day off or other scheduling notes"></textarea></label><button class="employee-hr-wide">Send next-week preference</button></form></details></div>'+
    '<h3>My request history</h3><p class="employee-hr-note">Latest 100 records per request category. All decisions remain available to HR by reporting month.</p><div class="employee-hr-history">'+([...d.requests||[],...d.leaves||[]].sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).map(employeeHrRequestHistory).join('')||'<p class="employee-hr-note">No requests yet.</p>')+'</div><h3>My verbal actions</h3><div class="employee-hr-history">'+((d.action_history||[]).map(action=>'<article class="employee-hr-history-card" data-live-key="action:'+E(action.id)+'"><strong>'+E(action.action_date)+'</strong><p>'+E(action.message)+'</p><small>'+(action.acknowledged_at?'Acknowledged '+E(new Date(action.acknowledged_at).toLocaleString('en-GB',{timeZone:'Asia/Amman'})):'Awaiting acknowledgment')+'</small></article>').join('')||'<p class="employee-hr-note">No verbal actions.</p>')+'</div>');
  const submit=async(form,path,body)=>{
    if(employeeHrMutating)return;employeeHrMutating=true;employeeHrGeneration++;const button=form.querySelector('button');button.disabled=true;
    try{await NewtelHrApi.call(path,{method:'POST',body});form.reset();notifyEmployeeHr();await loadEmployeeHr({force:true});employeeHrMessage('Request sent. Awaiting HR review.')}catch(error){employeeHrMessage(error.message,true)}finally{employeeHrMutating=false;button.disabled=false}
  };
  const sick=document.getElementById('employeeSickForm');sick.onsubmit=event=>{event.preventDefault();submit(sick,'/sick-leaves',new FormData(sick))};
  const annual=document.getElementById('employeeAnnualForm');annual.onsubmit=event=>{event.preventDefault();submit(annual,'/requests',{...Object.fromEntries(new FormData(annual)),request_type:'annual'})};
  const hourly=document.getElementById('employeeHourlyForm'),duration=hourly.elements.duration;
  const calculate=()=>{const start=hourly.elements.start_time.value;if(start&&duration.value!=='custom'){const n=Number(start.slice(0,2))*60+Number(start.slice(3))+Number(duration.value);hourly.elements.end_time.value=String(Math.floor(n/60)%24).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}hourly.elements.end_time.readOnly=duration.value!=='custom'};
  duration.onchange=calculate;hourly.elements.start_time.onchange=calculate;if(!hourly.elements.end_time.value)calculate();
  hourly.elements.start_date.onchange=async()=>{const day=hourly.elements.start_date.value;try{const result=await NewtelHrApi.call('/me/schedule?day='+encodeURIComponent(day));if(day!==hourly.elements.start_date.value)return;document.getElementById('employeeHourlyShift').textContent='Saved shift: '+(result.shift||'Not scheduled');hourly.elements.start_time.value=result.shift?.match(/^\d{2}:\d{2}/)?.[0]||'';calculate()}catch(error){employeeHrMessage(error.message,true)}};
  hourly.onsubmit=event=>{event.preventDefault();submit(hourly,'/requests',{...Object.fromEntries(new FormData(hourly)),end_date:hourly.elements.start_date.value,request_type:'short_leave'})};
  const week=document.getElementById('employeeWeekForm');
  week.querySelectorAll('[data-week-day]').forEach(select=>select.onchange=()=>select.parentElement.parentElement.querySelector('[data-week-custom]').hidden=select.value!=='custom');
  week.onsubmit=event=>{event.preventDefault();const days=[...week.querySelectorAll('[data-week-day]')].filter(select=>select.value).map(select=>({day:select.dataset.weekDay,value:select.value==='custom'?select.parentElement.parentElement.querySelector('[data-week-start]').value+' - '+select.parentElement.parentElement.querySelector('[data-week-end]').value:select.value}));if(!days.length)return employeeHrMessage('Select at least one preferred shift or day off.',true);submit(week,'/requests',{request_type:'schedule_preference',start_date:week.querySelector('[data-week-day]').dataset.weekDay,end_date:[...week.querySelectorAll('[data-week-day]')].at(-1).dataset.weekDay,week:days,note:week.elements.note.value})};
}
function showEmployeeHrAction(){
  let dialog=document.getElementById('employeeHrActionDialog');const action=employeeHrState?.warnings?.[0],decision=action?null:employeeHrState?.notifications?.[0],item=action||decision;
  if(!item){if(dialog?.open)dialog.close();return}if(dialog?.open&&dialog.dataset.actionId===item.id)return;
  if(!dialog){dialog=document.createElement('dialog');dialog.id='employeeHrActionDialog';dialog.className='employee-hr-action-dialog';dialog.dir='ltr';dialog.addEventListener('cancel',event=>event.preventDefault());document.body.appendChild(dialog)}
  NewtelLiveDom.html(dialog,'<span class="employee-hr-action-kicker">HR NOTIFICATION</span><h2>'+(action?'Verbal action':employeeHrKinds[decision.request_type]+' '+decision.status)+'</h2><small>'+employeeHrEsc(action?.action_date||decision.start_date)+'</small><p>'+employeeHrEsc(action?.message||decision.note||'HR has reviewed your request. The decision is saved in your profile.')+'</p>'+(decision?'<p>'+employeeHrEsc(decision.start_date)+' → '+employeeHrEsc(decision.end_date)+(decision.start_time?' · '+employeeHrEsc(decision.start_time)+' – '+employeeHrEsc(decision.end_time):'')+'</p>':'')+'<p class="employee-hr-note">'+(action?'Your acknowledgment time will be recorded.':'See your profile for the full request history.')+'</p><div role="status" id="employeeHrAckError"></div><button type="button">'+(action?'I acknowledge receipt':'Got it')+'</button>');
  dialog.dataset.actionId=item.id;dialog.querySelector('button').onclick=async()=>{if(employeeHrMutating)return;employeeHrMutating=true;employeeHrGeneration++;const button=dialog.querySelector('button');button.disabled=true;
    try{const result=await NewtelHrApi.call(action?'/actions/'+encodeURIComponent(action.id)+'/ack':'/'+decision.kind+'/'+encodeURIComponent(decision.id)+'/seen',{method:'POST'});if(action){employeeHrState.warnings=employeeHrState.warnings.filter(row=>row.id!==action.id);const history=employeeHrState.action_history?.find(row=>row.id===action.id);if(history)history.acknowledged_at=result.acknowledged_at}else employeeHrState.notifications=employeeHrState.notifications.filter(row=>row.id!==decision.id);dialog.close();renderEmployeeHrProfile();showEmployeeHrAction();notifyEmployeeHr()}catch(error){document.getElementById('employeeHrAckError').textContent=error.message;button.disabled=false}finally{employeeHrMutating=false}};
  if(!dialog.open)dialog.showModal();
}
function loadEmployeeHr({force=false}={}){
  if(typeof currentUser==='undefined'||!currentUser?.username)return Promise.resolve();
  if(employeeHrPending){if(force||!employeeHrState)employeeHrQueued=true;return employeeHrPending}
  employeeHrLoading=true;
  const username=currentUser.username,generation=employeeHrGeneration;
  employeeHrPending=(async()=>{try{const data=await NewtelHrApi.call('/me');if(currentUser?.username!==username||generation!==employeeHrGeneration)return;employeeHrState=data;employeeHrOffset=Date.parse(data.server_now)-Date.now();renderEmployeeHr()}catch(error){if(currentUser?.username!==username||generation!==employeeHrGeneration)return;const node=document.getElementById('employeeHrCard');if(node&&!employeeHrState)NewtelLiveDom.html(node,'<h2>My attendance</h2><div id="employeeHrMessage" role="status"></div>');employeeHrMessage(error.message,true)}})().finally(()=>{employeeHrLoading=false;employeeHrPending=null;if(employeeHrQueued){employeeHrQueued=false;return loadEmployeeHr()}});
  return employeeHrPending;
}
async function checkEmployeeHr(){
  if(document.hidden||globalThis.NewTelIdle?.isPaused()||employeeHrLoading||employeeHrMutating||employeeHrChecking||typeof currentUser==='undefined'||!currentUser?.username)return;
  if(!employeeHrState)return loadEmployeeHr();
  employeeHrChecking=true;const generation=employeeHrGeneration;
  try{const check=await NewtelHrApi.call('/me/check');if(generation!==employeeHrGeneration)return;const windowEnd=employeeHrState.shift?.match(/-\s*(\d{2}:\d{2})$/),previousEnded=employeeHrState.day<check.today&&!employeeHrState.attendance?.punch_in&&windowEnd&&Date.parse(check.server_now)>=Date.parse(`${check.today}T${windowEnd[1]}:00+03:00`);employeeHrOffset=Date.parse(check.server_now)-Date.now();updateEmployeeWork();if(check.revision!==employeeHrState.revision||check.today!==employeeHrState.today||previousEnded)await loadEmployeeHr()}catch{/* Keep loaded data on temporary network failure. */}finally{employeeHrChecking=false}
}
function resetEmployeeHr(){employeeHrGeneration++;employeeHrQueued=false;employeeHrState=null;document.getElementById('employeeHrActionDialog')?.remove();const node=document.getElementById('employeeHrCard');if(node)node.replaceChildren();document.getElementById('employeeHrProfile')?.replaceChildren()}
employeeHrChannel?.addEventListener('message',checkEmployeeHr);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkEmployeeHr()});
globalThis.addEventListener('newtel:idle-resume',checkEmployeeHr);
setInterval(checkEmployeeHr,10000);
