import {hrDay,hrAttendanceStatus,hrPresence,hrShiftValue,hrShiftWindow} from './hr-core.js';
const $=id=>document.getElementById(id),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={data:null,view:'attendance',presence:[],offset:0,busy:false,checking:false,mutating:false,pending:null,reloadRequested:false};
const hrChannel=typeof BroadcastChannel==='function'?new BroadcastChannel('newtel-hr-updates'):null;
function notifyHrChange(){hrChannel?.postMessage({changed:true})}
function renderPreservingDrafts(){
  const holder=$('hrView'),form=$('hrActionForm'),dirtyForm=form?.dataset.dirty==='1'?form:null;
  const cells=[...holder.querySelectorAll('[data-schedule-day][data-dirty="1"]')],openPeople=[...holder.querySelectorAll('[data-schedule-person][open]')].map(node=>node.dataset.schedulePerson);
  if(dirtyForm)dirtyForm.remove();cells.forEach(node=>node.remove());render();
  if(dirtyForm&&$('hrActionForm'))$('hrActionForm').replaceWith(dirtyForm);
  for(const cell of cells){const target=[...holder.querySelectorAll('[data-schedule-day]')].find(node=>node.dataset.scheduleUser===cell.dataset.scheduleUser&&node.dataset.scheduleDay===cell.dataset.scheduleDay);if(target)target.replaceWith(cell)}
  holder.querySelectorAll('[data-schedule-person]').forEach(node=>{if(openPeople.includes(node.dataset.schedulePerson))node.open=true});
}
async function deleteHrRecord(kind,id){
  if(state.mutating)return;
  const prompt=kind==='actions'?'حذف التنبيه الشفوي نهائيًا؟ سيختفي من حساب الموظف.':'حذف الإجازة المرضية ومرفقها نهائيًا؟ إذا كانت معتمدة ستُعاد مقارنة الحضور بدونها.';
  if(!confirm(prompt))return;state.mutating=true;
  try{const result=await NewtelHrApi.call('/'+kind+'/'+encodeURIComponent(id),{method:'DELETE'});notifyHrChange();await load();message(result.file_cleanup_pending?'تم حذف الإجازة. تنظيف المرفق سيُعاد تلقائيًا.':'تم الحذف وتحديث البيانات.')}catch(error){message(error.message,true)}finally{state.mutating=false}
}
const titles={attendance:'حضور الفريق',online:'الأيجنت المتصلون',schedule:'جدول الأسبوع',actions:'الإجراءات الشفوية',leaves:'الإجازات المرضية'};
const labels={late:'متأخر',present:'حاضر',checked_out:'سجّل الخروج',missing_login:'لم يسجّل الدخول',absent:'غياب',off:'أوف',upcoming:'لم يبدأ الدوام',not_scheduled:'لا يوجد جدول',sick_leave:'إجازة مرضية معتمدة',pending:'بانتظار المراجعة',approved:'معتمدة',rejected:'مرفوضة'};
const colors={late:'yellow',missing_login:'red',absent:'red',present:'green',checked_out:'green',sick_leave:'green',pending:'yellow',approved:'green',rejected:'red'};
const time=value=>value?new Date(value).toLocaleTimeString('ar-JO',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Amman'}):'—';
const dateLabel=day=>new Date(day+'T12:00:00Z').toLocaleDateString('ar-JO',{weekday:'short',day:'2-digit',month:'short',timeZone:'Asia/Amman'});
const presets=Object.fromEntries(Array.from({length:16},(_,i)=>{const letter=String.fromCharCode(65+i),start=String((8+i)%24).padStart(2,'0')+':00';return [[letter,`${start} - ${String((17+i)%24).padStart(2,'0')}:00`],[letter+letter,`${start} - ${String((20+i)%24).padStart(2,'0')}:00`]]}).flat());
function message(text,error=false){$('hrMessage').textContent=text;$('hrMessage').classList.toggle('error',error)}
function badge(status){return `<span class="hr-badge ${colors[status]||''}">${esc(labels[status]||status)}</span>`}
function person(user){return `<div class="hr-person"><span class="hr-avatar">${esc(String(user.full_name||user.username).split(/\s+/).slice(0,2).map(p=>p[0]).join(''))}</span><div><strong>${esc(user.full_name||user.username)}</strong><small>${esc(user.username)} · ${esc(user.role)}</small></div></div>`}
function roster(){return state.data.roster.map(row=>({...row,...hrAttendanceStatus({day:row.attendance_day||state.data.day,shift:row.shift,attendance:row.attendance,leave:row.leave,grace:state.data.grace,now:Date.now()+state.offset}),online:state.presence.some(item=>item.username===row.username&&hrPresence(item,Date.now()+state.offset)==='online')}))}
function render(){
  const data=state.data;if(!data)return;
  $('hrPageTitle').textContent=titles[state.view];
  document.querySelectorAll('[data-view]').forEach(button=>{const selected=button.dataset.view===state.view;button.classList.toggle('active',selected);selected?button.setAttribute('aria-current','page'):button.removeAttribute('aria-current')});
  const people=roster(),counts=[['المتصلون',people.filter(p=>p.online).length],['الحاضرون',people.filter(p=>['present','late','checked_out'].includes(p.status)).length],['المتأخرون',people.filter(p=>p.late_minutes>0&&p.attendance?.punch_in).length],['لم يسجّلوا / غياب',people.filter(p=>['missing_login','absent'].includes(p.status)).length]];
  $('hrMetrics').innerHTML=counts.map(([name,value])=>`<div><small>${name}</small><strong>${value}</strong></div>`).join('');
  const holder=$('hrView');
  if(['attendance','online'].includes(state.view)){
    const rows=state.view==='online'?people.filter(p=>p.online):people;
    holder.innerHTML=`<div class="hr-grid">${rows.map(user=>`<article class="hr-card">${person(user)}${state.view==='online'?'<span class="hr-badge green">متصل الآن</span>':badge(user.status)}${user.late_minutes?`<p>تأخير ${user.late_minutes} دقيقة ${user.attendance?'':'عن الدخول المجدول'}</p>`:''}<div class="hr-details"><div><small>الجدول</small><strong>${esc(user.shift||'غير محدد')}</strong></div><div><small>حالة الاتصال</small><strong>${user.online?'متصل':'غير متصل'}</strong></div><div><small>البصمة · دخول</small><strong>${time(user.attendance?.punch_in)}</strong></div><div><small>البصمة · خروج</small><strong>${time(user.attendance?.punch_out)}</strong></div></div></article>`).join('')||'<div class="hr-empty">لا يوجد موظفون متصلون الآن.</div>'}</div>`;
  }else if(state.view==='schedule'){
    holder.innerHTML=people.map(user=>`<details class="hr-card hr-schedule" data-schedule-person="${esc(user.username)}" style="margin-bottom:14px"><summary>${esc(user.full_name)} · ${esc(user.role)}</summary><div class="hr-week">${data.dates.map(day=>{const value=hrShiftValue(data.controls,user.username,day),code=value==='OFF'?'OFF':Object.keys(presets).find(k=>presets[k]===value)||'MAN',times=value.match(/(\d{2}:\d{2}) - (\d{2}:\d{2})/);return `<div class="hr-week-day" data-schedule-user="${esc(user.username)}" data-schedule-day="${day}"><strong>${esc(dateLabel(day))}</strong>${data.can_manage?`<select data-shift-code aria-label="شفت ${esc(user.full_name)} ${day}"><option value="" ${!value?'selected':''}>غير مجدول</option>${['OFF',...Object.keys(presets),'MAN'].map(k=>`<option value="${k}" ${value&&code===k?'selected':''}>${k==='OFF'?'أوف':k==='MAN'?'يدوي':k+' · '+presets[k].slice(0,5)}</option>`).join('')}</select><div class="hr-times" ${code==='MAN'&&value?'':'hidden'}><input type="time" data-start aria-label="بداية الدوام" value="${times?.[1]||''}"><input type="time" data-end aria-label="نهاية الدوام" value="${times?.[2]||''}"></div><button data-save-shift>حفظ اليوم</button>`:`<small>${esc(value||'غير مجدول')}</small>`}</div>`}).join('')}</div></details>`).join('');
    holder.querySelectorAll('[data-shift-code]').forEach(select=>select.onchange=()=>select.closest('[data-schedule-day]').querySelector('.hr-times').hidden=select.value!=='MAN');
    holder.querySelectorAll('[data-save-shift]').forEach(button=>button.onclick=async()=>{if(state.mutating)return;const cell=button.closest('[data-schedule-day]'),code=cell.querySelector('select').value,value=code==='OFF'?'OFF':presets[code]||`${cell.querySelector('[data-start]').value} - ${cell.querySelector('[data-end]').value}`;if(!code)return message('اختر شفتًا أو أوف.',true);button.disabled=true;state.mutating=true;try{await NewtelHrApi.call('/schedule',{method:'POST',body:{username:cell.dataset.scheduleUser,day:cell.dataset.scheduleDay,value}});cell.dataset.dirty='0';notifyHrChange();await load();message('تم حفظ الشفت وتحديث الجدول.')}catch(error){message(error.message,true)}finally{button.disabled=false;state.mutating=false}});
  }else if(state.view==='actions'){
    holder.innerHTML=(data.can_manage?`<form class="hr-form" id="hrActionForm"><h2>تسجيل إجراء شفوي</h2><label>الموظف<select name="username" required>${people.map(p=>`<option value="${esc(p.username)}">${esc(p.full_name)}</option>`).join('')}</select></label><label>التاريخ<input type="date" name="day" required value="${data.day}"></label><label>تفاصيل الإجراء<textarea name="message" required minlength="3" maxlength="2000"></textarea></label><button>إرسال للموظف</button></form>`:'')+`<div class="hr-grid">${data.actions.map(action=>`<article class="hr-card"><h3>${esc(people.find(p=>p.username===action.username)?.full_name||action.username)}</h3><time>${esc(action.action_date)}</time><p>${esc(action.message)}</p><span class="hr-badge ${action.acknowledged_at?'green':'yellow'}">${action.acknowledged_at?'أقرّ الموظف بالاطلاع':'بانتظار إقرار الموظف'}</span>${action.acknowledged_at?`<p>${esc(new Date(action.acknowledged_at).toLocaleString('ar-JO',{timeZone:'Asia/Amman'}))}</p>`:''}</article>`).join('')||'<div class="hr-empty">لا توجد إجراءات لهذا الأسبوع.</div>'}</div>`;
    holder.querySelectorAll('article.hr-card').forEach((card,index)=>{if(data.can_manage){const button=document.createElement('button');button.className='hr-reject';button.textContent='حذف التنبيه';button.onclick=()=>deleteHrRecord('actions',data.actions[index].id);card.appendChild(button)}});
    const form=$('hrActionForm');if(form)form.onsubmit=async event=>{event.preventDefault();if(state.mutating)return;const button=form.querySelector('button');button.disabled=true;state.mutating=true;try{await NewtelHrApi.call('/actions',{method:'POST',body:Object.fromEntries(new FormData(form))});form.dataset.dirty='0';notifyHrChange();await load();message('تم إرسال الإجراء؛ يصل تلقائيًا للموظف خلال 10 ثوانٍ أثناء فتح الموقع.')}catch(error){message(error.message,true)}finally{button.disabled=false;state.mutating=false}};
  }else{
    holder.innerHTML=`<div class="hr-grid">${data.leaves.map(leave=>`<article class="hr-card"><h3>${esc(people.find(p=>p.username===leave.username)?.full_name||leave.username)}</h3>${badge(leave.status)}<p>${esc(leave.start_date)} ← ${esc(leave.end_date)}</p>${leave.note?`<p>${esc(leave.note)}</p>`:''}<div class="hr-actions-row"><button data-leave-file="${esc(leave.id)}">عرض المرفق</button>${data.can_manage?`<button data-review="approved" data-id="${esc(leave.id)}">اعتماد</button><button class="hr-reject" data-review="rejected" data-id="${esc(leave.id)}">رفض</button>`:''}</div></article>`).join('')||'<div class="hr-empty">لا توجد إجازات مرضية لهذا الأسبوع.</div>'}</div>`;
    holder.querySelectorAll('[data-leave-file]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{const blob=await NewtelHrApi.call(`/sick-leaves/${encodeURIComponent(button.dataset.leaveFile)}/file`,{file:true}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='sick-leave.'+(blob.type==='application/pdf'?'pdf':blob.type==='image/png'?'png':'jpg');link.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(error){message(error.message,true)}finally{button.disabled=false}});
    holder.querySelectorAll('article.hr-card').forEach((card,index)=>{if(data.can_manage){const button=document.createElement('button');button.className='hr-reject';button.textContent='حذف الإجازة';button.onclick=()=>deleteHrRecord('sick-leaves',data.leaves[index].id);card.querySelector('.hr-actions-row').appendChild(button)}});
    holder.querySelectorAll('[data-review]').forEach(button=>button.onclick=async()=>{if(state.mutating||!confirm('تأكيد '+(button.dataset.review==='approved'?'اعتماد':'رفض')+' الإجازة؟'))return;button.disabled=true;state.mutating=true;try{await NewtelHrApi.call('/sick-leaves/'+encodeURIComponent(button.dataset.id),{method:'PATCH',body:{status:button.dataset.review}});notifyHrChange();await load();message('تم تحديث قرار الإجازة.')}catch(error){message(error.message,true)}finally{button.disabled=false;state.mutating=false}});
  }
  holder.oninput=event=>{const node=event.target.closest('[data-schedule-day],#hrActionForm');if(node)node.dataset.dirty='1'};
  holder.onchange=holder.oninput;
}
function load(){
  if(state.busy){state.reloadRequested=true;return state.pending}state.busy=true;$('hrRefresh').disabled=true;const selectedDay=$('hrDay').value;
  state.pending=(async()=>{try{const data=await NewtelHrApi.call('/dashboard?day='+encodeURIComponent(selectedDay));if(selectedDay!==$('hrDay').value)return;state.data=data;state.presence=data.presence||[];state.offset=Date.parse(data.server_now)-Date.now();$('hrName').textContent=data.profile.full_name||data.profile.username;$('hrPermission').textContent=data.can_manage?'HR Admin · إدارة':'HR · عرض فقط';renderPreservingDrafts()}catch(error){message(error.message,true);if(!state.data)$('hrView').innerHTML='<div class="hr-empty">تأكد من تسجيل الدخول بحساب HR. <a href="ebook.html">العودة إلى eBook</a></div>'}})().finally(()=>{state.busy=false;state.pending=null;$('hrRefresh').disabled=false;if(state.reloadRequested||selectedDay!==$('hrDay').value){state.reloadRequested=false;return load()}});
  return state.pending;
}
async function check(){
  if(document.hidden||globalThis.NewTelIdle?.isPaused()||!state.data||state.busy||state.mutating||state.checking)return;
  state.checking=true;
  try{const data=await NewtelHrApi.call('/check');state.presence=data.presence;state.offset=Date.parse(data.server_now)-Date.now();const transition=state.data.roster.some(row=>row.attendance_day&&row.attendance_day!==state.data.day&&Date.parse(data.server_now)>=(hrShiftWindow(row.attendance_day,row.shift)?.end||Infinity));if(data.revision!==state.data.revision||transition)await load();else if(['attendance','online'].includes(state.view))render()}catch(error){message(error.message,true)}finally{state.checking=false}
}
$('hrDay').value=hrDay();$('hrDay').onchange=load;$('hrRefresh').onclick=load;
$('hrLogout').onclick=()=>NewtelHrApi.logout();
document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{state.view=button.dataset.view;render()});
hrChannel?.addEventListener('message',check);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)check()});globalThis.addEventListener('newtel:idle-resume',check);setInterval(check,10000);load();
