#!/usr/bin/env node
import tls from "node:tls";import fs from "node:fs";import {UcmClient,createNodeTransport} from "./ucm-api.mjs";
const required=name=>{const value=process.env[name];if(!value)throw new Error(`${name} is required`);return value},command=process.argv[2]||"health",caFile=process.env.UCM_CA_FILE,ca=caFile?fs.readFileSync(caFile):undefined,allow=process.env.UCM_ALLOW_SELF_SIGNED_DEV==="true"&&process.env.NODE_ENV!=="production";
const check=async(label,value)=>new Promise(resolve=>{if(!value)return resolve({service:label,status:"not_configured"});const url=new URL(value),socket=tls.connect({host:url.hostname,port:Number(url.port||443),servername:url.hostname,ca,rejectUnauthorized:!allow},()=>{socket.end();resolve({service:label,status:"reachable",tls_authorized:socket.authorized})});socket.setTimeout(5000,()=>socket.destroy(new Error("timeout")));socket.on("error",()=>resolve({service:label,status:"unreachable"}))});
if(command==="health"){console.log(JSON.stringify(await check("https_api_8089",process.env.UCM_API_BASE_URL)));console.log(JSON.stringify(await check("legacy_cdr_8443",process.env.UCM_CDR_BASE_URL)));process.exit(0)}
const client=new UcmClient({apiBaseUrl:required("UCM_API_BASE_URL"),cdrBaseUrl:process.env.UCM_CDR_BASE_URL||"",cdrMode:process.env.UCM_CDR_MODE||"auto",username:required("UCM_API_USERNAME"),password:required("UCM_API_PASSWORD"),cdrUsername:process.env.UCM_CDR_USERNAME||process.env.UCM_API_USERNAME,cdrPassword:process.env.UCM_CDR_PASSWORD||process.env.UCM_API_PASSWORD,transport:createNodeTransport({caFile,allowSelfSignedDev:allow})});
if(command==="login"){await client.login();console.log(JSON.stringify({service:"ucm_https_api",status:"authenticated"}));process.exit(0)}
if(command==="sample"){const from=process.argv[3],to=process.argv[4];if(!from||!to)throw new Error("Usage: node connector/ucm-verify.mjs sample START END");const rows=await client.cdrPage({start:from,end:to,limit:1});const row=rows[0];console.log(JSON.stringify({service:"ucm_cdr",status:"ok",mode:client.lastCdrMode,records:rows.length,sample:row?{has_session:Boolean(row.session||row.AcctId),started_at:row.start||row.start_time||null,disposition:row.disposition||null}:null}));process.exit(0)}
throw new Error("Commands: health | login | sample START END");
